name: CI

on:
  pull_request:
    branches: ["**"]
  push:
    branches: [main]

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Run tests with coverage
        run: pnpm test:coverage

      - name: Report test coverage
        uses: davelosert/vitest-coverage-report-action@v2

      - name: Run knip
        run: pnpm run knip
